### ISSUE TITLE
The command line is too long.

### ISSUE THREAD

**Issue by ecellini** [jsteinshouer/commandbox-cflint#4]
Hello,
thank you for "commandbox-cflint"!
I have a issue when try to use CFLINT for medium project, the Windows Powershell show: 
"The command line is too long."

I use: Windows 10 + Powershell + Commandbox 4.2.0

the command is "cflint **.cfc --html"

Can you help me?

**Comment by jsteinshouer** [comment]
Thanks for submitting the issue. I have run across this on Windows before when running cflint on a folder with a lot of cfc/cfm files. The CFLint project now has a Java API for calling CFlint so I would not have to call it via a command which should fix this. I will take look and see how difficult it would be to make this change. 

How many cfc files are in the directory you are trying to run CFLint on? Are there any files or folders that you would want to exclude from running linting?

**Comment by ecellini** [comment]
Hello,
thank you for response.

I have 537 files in this project, at this moment I do not have any folder to exclude.

There is any command to add (ex debug) for read the command was generated and see how long?

Is the possible fix is use "-folder" param instead "-file" on file cflint.cfc line 214?

**Comment by evagoras** [comment]
Running into the same issue, so the Java API solution would come in handy!

**Comment by jsteinshouer** [comment]
@ecellini @evagoras I released some changes to run CFLint via the Java API instead of the command line which should fix this issue. Please install the latest when you have a moment and let me know if it is working better for you. It requires CommandBox 4 or above. Thanks for reporting the issue.

**Comment by ecellini** [comment]
Thank you @jsteinshouer!

Now CFLINT run correct!

I have only a little issue.
I would like use CFLINT for 2 project: Project1 and Project2.

open CommanBox and write
cd \Project\Project1
cflint **.cfc --html >> CFLINT  show "Report generated at C:\Project\Project1\/cflint-results.html"

now write
cd \Project\Project2
cflint **.cfc --html >> CFLINT  show "Report generated at C:\Project\Project1\/cflint-results.html"

CFLINT don't run on Project2 but still on Project1.

If I open another CommanBox it's run correctly on Project2.

Thank you!

**Comment by jsteinshouer** [comment]
@ecellini I released a fix for that issue. Thanks for reporting.
