### ISSUE TITLE
Support junit xml format for CI reports?

### ISSUE THREAD

**Issue by michaelborn** [jsteinshouer/commandbox-cflint#7]
Wondering how much work it would be to add junit-style xml report to commandbox-cflint? This tool is awesome for CI, and it would be a little bit nicer if it had a junit XML output. My tool of choice is Bitbucket Pipelines, but [other CI tools support them as well](https://docs.gitlab.com/ee/ci/junit_test_reports.html).

It looks like the junit XML format is something like this: https://llg.cubic.org/docs/junit/

**Comment by jsteinshouer** [comment]
I have seen JUnit used for reporting unit test results for Jenkins but had not thought about using is for Static Analysis as well. Have you seen this with other linting tools? 

So the benefit would be that it would provide a nice report of the results in Bitbucket Pipelines or other CI systems? I have not looked at it too close yet but I don't think it would be that difficult. Do you envision the output looking something like this?

```
<testsuites package="CFLint">
	<testsuite name="/absolute/path/to/MyComponent.cfc">
		<testcase name="COMPONENT_HINT_MISSING">
			<failure type="WARNING" message="Component MyComponent is missing a hint"><![CDATA[line 1, col 1, Warning - Component MyComponent is missing a hint.]]></failure>
		</testcase>
		<testcase name="CFQUERYPARAM_REQ">
			<failure type="error" message="&lt;cfquery&gt; should use &lt;cfqueryparam/&gt; for variable 'arguments.something'"><![CDATA[line 432, col 0, Error - <cfquery> should use <cfqueryparam> for variable 'arguments.something'.]]></failure>
		</testcase>
	</testsuite>
</testsuites>
```

Would you want it to report a failure for all the CFLint rule levels (ERROR, WARNING, and INFO)?

**Comment by michaelborn** [comment]
Looks like it was implemented this May in the Golang linter: https://github.com/golangci/golangci-lint I'm having trouble finding other examples, though.

Yes, it would basically be a prettier way to show the cflint results in Bitbucket or other CI platforms. It's not a deal breaker by any means, merely a nice-to-have, but if it's not too hard I thought it would be handy for use in CI. I'm actually working on a CI guide for Bitbucket and ColdFusion, and noticed that both TestBox and Fixinator support junit xml reports. (Of course, as you mentioned, those are not static analysis tools.)

In Bitbucket, that would look something like this:
<img width="1360" alt="tests+result+log+view" src="https://user-images.githubusercontent.com/8106227/60022245-6f9c0200-9661-11e9-8f56-76139b921a2a.png">

**Comment by jsteinshouer** [comment]
I added a flag for generating a JUnit report in the junit-report branch. Would mind installing from there and checking it out for me?
```
box install https://github.com/jsteinshouer/commandbox-cflint#junit-report
```

You can generate the xml file by passing the `--junit` flag.

**Comment by michaelborn** [comment]
I'll definitely give this a whirl and send you a demo on Bitbucket, thank you!

**Comment by michaelborn** [comment]
So, I got slightly tripped up on this - that `box install` command should be `box install jsteinshouer/commandbox-cflint#junit-report`.

Here's the demo on Bitbucket Pipelines. https://bitbucket.org/michaelborn_me/cfevents/addon/pipelines/home#!/results/23. It looks like Bitbucket Pipelines didn't understand the file. Here's the relevant portion of the build log:

```
Found matching test report file /opt/atlassian/pipelines/agent/build/test-results/cflint-results.xml
Located test suite containing 0 tests, with 0 failures and 3 errors.
Finished scanning for test reports. Found 1 test report files.
Merged test suites, total number tests is 0, with 0 failures and 3 errors.
```

**Comment by jsteinshouer** [comment]
I just have it in a feature branch currently to test it out. I have only tested in Jenkins. 

When I click the link you provided I see an error "No such file or directory". Are the issue and pull request you entered related to this?

The snippet of build log you provided seems to indicate it recognized 3 errors from the file. Are you thinking they should be recognized as failures instead?

**Comment by jsteinshouer** [comment]
I added the code to this branch that removes the file extension if it exists in the filename. Do you want to give that a try and see if it works better?

**Comment by michaelborn** [comment]
> "When I click the link you provided I see an error "No such file or directory". Are the issue and pull request you entered related to this?"

No, not related. I was expecting CFLint to create the directory specified if it didn't exist - instead, CFLint threw an error because that output dir didn't exist. That's a separate issue and easy to work around.

Here's a [better (cleaner) example](https://bitbucket.org/michaelborn_me/cfevents/addon/pipelines/home#!/results/26), which shows that CFLint found 3 errors and Bitbucket Pipelines decided not to do anything with it. As far as I can tell, BP will only "halt" the build and show the junit results if it detects failures - not errors. I'm not sure if using `failure` instead of (or in addition to) `error` is a good precedent to set.

Actually, after looking at it more, it seems that `<failure>` is probably the way to go. The Gitlab docs link to [this page](https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_14.1.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html), which uses `<failure>` and doesn't mention `<error>`. [This link](https://llg.cubic.org/docs/junit/) explains the difference between a test error:
> "An errored test is one that had an unanticipated problem. For example an unchecked throwable or a problem with the implementation of the test. "

and a test failure:

> "Indicates that the test failed. A failure is a test which the code has explicitly failed by using the mechanisms for that purpose. For example via an assertEquals."

**Comment by jsteinshouer** [comment]
@michaelborn Thanks for the feedback. I am actually using `<failure` instead of `<error>`

https://github.com/jsteinshouer/commandbox-cflint/blob/d67e99d7ff21ddc3fa2bdf7b8ed2b978f454d7ca/models/JUnitReporter.cfc#L44

I will see if I can get it working with Bitbucket pipelines and let you know.

**Comment by jsteinshouer** [comment]
It looks like the problem was that I was not including the test count for the testsuite. I made that change and tested it in Bitbucket pipelines. I went ahead and merged it in and released it.
